In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

from sklearn.datasets import load_diabetes
from sklearn.preprocessing import OrdinalEncoder

from featimp import (
    get_corr_importances,
    get_chi2_crosstab_importances,
    get_chi2_importances,
    get_anova_importances,
    get_mutual_info_importances,
    get_ml_importances,
    get_permutation_importances,
    get_feature_importances,
    )

sns.set()
warnings.simplefilter("ignore")
cm = sns.color_palette("coolwarm", as_cmap=True)

In [2]:
column_a = np.random.rand(1, 1000)
column_b = np.random.rand(1, 1000)
column_c = np.random.randint(2, size=1000)
column_d = np.random.randint(10, size=1000)
column_e = np.random.normal(0, 1, size=1000)
column_f = np.random.choice([True, False], 1000)
column_g = np.random.choice([1, 0], 1000)
test_df = pd.DataFrame()
test_df['a'] = column_a[0]
test_df['b'] = column_b[0]
test_df['c'] = column_c
test_df['d'] = column_d
test_df['e'] = column_e
test_df['f'] = column_f
test_df['g'] = column_g
test_df['target_reg'] = column_a[0]
test_df['target_clf_binary'] = column_c
test_df['target_clf_multi'] = column_d
display(test_df.head())

,a,b,c,d,e,f,g,target_reg,target_clf_binary,target_clf_multi
0,0.657793,0.376991,1,0,0.743753,False,1,0.657793,1,0
1,0.477385,0.646920,1,5,-1.181454,True,1,0.477385,1,5
2,0.060299,0.820574,1,1,-2.511020,True,0,0.060299,1,1
3,0.148096,0.822287,1,0,-0.683230,True,0,0.148096,1,0
4,0.089420,0.992849,1,1,0.227742,True,0,0.089420,1,1

In [3]:
fi_temp_df = get_feature_importances(data=test_df, num_features=['a', 'b', 'e'], cat_features=[], target='target_reg', task='reg', method='all')
fi_temp_df.style.background_gradient(cmap=cm)

In [4]:
fi_temp_df = get_feature_importances(data=test_df, num_features=['a', 'b', 'e'], cat_features=[], target='target_clf_binary', task='clf_binary', method='all')
fi_temp_df.style.background_gradient(cmap=cm)

In [5]:
fi_temp_df = get_feature_importances(data=test_df, num_features=['a', 'b', 'e'], cat_features=[], target='target_clf_multi', task='clf_multiable', method='all')
fi_temp_df.style.background_gradient(cmap=cm)

In [6]:
fi_temp_df = get_feature_importances(data=test_df, num_features=[], cat_features=['c', 'd'], target='target_reg', task='reg', method='all')
fi_temp_df.style.background_gradient(cmap=cm)

In [7]:
fi_temp_df = get_feature_importances(data=test_df, num_features=[], cat_features=['c', 'd'], target='target_clf_binary', task='clf_binary', method='all')
fi_temp_df.style.background_gradient(cmap=cm)

In [8]:
fi_temp_df = get_feature_importances(data=test_df, num_features=[], cat_features=['c', 'd'], target='target_clf_multi', task='clf_multiable', method='all')
fi_temp_df.style.background_gradient(cmap=cm)

In [9]:
fi_temp_df = get_feature_importances(data=test_df, num_features=[], cat_features=[], bool_features=['f', 'g'], target='target_reg', task='reg', method='all')
fi_temp_df.style.background_gradient(cmap=cm)

In [10]:
fi_temp_df = get_feature_importances(data=test_df, num_features=[], cat_features=[], bool_features=['f', 'g'], target='target_clf_binary', task='clf_binary', method='all')
fi_temp_df.style.background_gradient(cmap=cm)

In [11]:
fi_temp_df = get_feature_importances(data=test_df, num_features=[], cat_features=[], bool_features=['f', 'g'], target='target_clf_multi', task='clf_multiable', method='all')
fi_temp_df.style.background_gradient(cmap=cm)