In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

from sklearn.datasets import load_diabetes
from sklearn.preprocessing import OrdinalEncoder

from featimp import (
    get_corr_importances,
    get_chi2_crosstab_importances,
    get_chi2_importances,
    get_anova_importances,
    get_mutual_info_importances,
    get_ml_importances,
    get_permutation_importances,
    get_feature_importances,
    )

sns.set()
warnings.simplefilter("ignore")
cm = sns.light_palette("green", as_cmap=True)

In [19]:
column_a = np.random.rand(1, 1000)
column_b = np.random.rand(1, 1000)
column_c = np.random.randint(2, size=1000)
column_d = np.random.randint(10, size=1000)
column_e = np.random.normal(0, 1, size=1000)
test_df = pd.DataFrame()
test_df['a'] = column_a[0]
test_df['b'] = column_b[0]
test_df['c'] = column_c
test_df['d'] = column_d
test_df['e'] = column_e
test_df['target_reg'] = column_a[0]
test_df['target_clf_binary'] = column_c
test_df['target_clf_multi'] = column_d
display(test_df.head())

,a,b,c,d,e,target_reg,target_clf_binary,target_clf_multi
0,0.728332,0.501019,1,1,0.246834,0.728332,1,1
1,0.326255,0.736472,0,8,-0.587401,0.326255,0,8
2,0.421116,0.804867,1,5,-0.188332,0.421116,1,5
3,0.524131,0.935239,0,8,-1.186317,0.524131,0,8
4,0.204897,0.932672,0,9,-1.921467,0.204897,0,9

In [20]:
fi_temp_df = get_feature_importances(data=test_df, num_features=['a', 'b', 'e'], cat_features=[], target='target_reg', task='reg', method='all')
fi_temp_df.style.background_gradient(cmap=cm)

In [21]:
fi_temp_df = get_feature_importances(data=test_df, num_features=['a', 'b', 'e'], cat_features=[], target='target_clf_binary', task='clf_binary', method='all')
fi_temp_df.style.background_gradient(cmap=cm)

In [22]:
fi_temp_df = get_feature_importances(data=test_df, num_features=['a', 'b', 'e'], cat_features=[], target='target_clf_multi', task='clf_multiable', method='all')
fi_temp_df.style.background_gradient(cmap=cm)

In [23]:
fi_temp_df = get_feature_importances(data=test_df, num_features=[], cat_features=['c', 'd'], target='target_reg', task='reg', method='all')
fi_temp_df.style.background_gradient(cmap=cm)

In [24]:
fi_temp_df = get_feature_importances(data=test_df, num_features=[], cat_features=['c', 'd'], target='target_clf_binary', task='clf_binary', method='all')
fi_temp_df.style.background_gradient(cmap=cm)

In [25]:
fi_temp_df = get_feature_importances(data=test_df, num_features=[], cat_features=['c', 'd'], target='target_clf_multi', task='clf_multiable', method='all')
fi_temp_df.style.background_gradient(cmap=cm)